### ISSUE TITLE
Error: binding.value is not a function

### ISSUE THREAD

**Issue by alphatrust-dev** [hybridwebdev/hover-intent-vue#2]
I'm getting this error:

`Error: binding.value is not a function`

On this line:
![image](https://user-images.githubusercontent.com/23238954/94619384-70631100-0272-11eb-8e23-dc99e444b3f5.png)

`<div id="VisibilityToggle" class="btn btn-lg btn-light btn-visibility" v-hover-intent="{ change: toggleTaskButtons, value: myValueToToggle }">`
&nbsp;&nbsp;&nbsp;&nbsp;`<i class="fa fa-eye-slash">`
`</div>`

...

`toggleTaskButtons(val) {
     console.log("val", val);
},`

**Comment by alexcroox** [comment]
Having the same issue, @hybridwebdev any ideas?

**Comment by alexcroox** [comment]
@alphatrust-dev this worked out the box for Vue v2 https://github.com/gabrieliuga/vue2-hover-intent

`v-hover-intent="changeActiveMegaMenuChildKey.bind(null, item.key)"`

**Comment by alphatrust-dev** [comment]
Hi @hybridwebdev - why was this issue closed?  Is there a solution?
